### ISSUE TITLE
Doesn't download default model and if I try and load a model it crashes after submitting prompt

### ISSUE THREAD

**Issue by aronnelson** [johnbean393/FileChat#1]
<img width="810" alt="SCR-20240614-jqyf" src="https://github.com/johnbean393/FileChat/assets/200755/b9133d10-00a5-4196-92b0-29767b14ee97">

**Comment by johnbean393** [comment]
Sorry for the delayed response. Let me look into this.

**Comment by johnbean393** [comment]
> <img alt="SCR-20240614-jqyf" width="810" src="https://private-user-images.githubusercontent.com/200755/339896854-b9133d10-00a5-4196-92b0-29767b14ee97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzODcxMTYsIm5iZiI6MTcxOTM4NjgxNiwicGF0aCI6Ii8yMDA3NTUvMzM5ODk2ODU0LWI5MTMzZDEwLTAwYTUtNDE5Ni05MmIwLTI5NzY3YjE0ZWU5Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNlQwNzI2NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZTdkOTVhMmVhODhlZjNiNWQyYzYzNDZmMzZhZTBjYjNiMjNjNGJkMGVhOTM1Mzg3MzcwYWFkNWFiNmQzYjJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AJanxcXRxaYIGduRP3uK3H7UOwFQFUQu79gaPW6pQRY">

What version of Xcode & macOS are you on?
